### ISSUE TITLE
求一下pt-tools源码

### ISSUE THREAD

**Issue by nashgoo** [wdjoys/docker-ubuntu#2]
fork了您的pttools在action运行了几天以后被官方删除了，请问能否发一下源码，打算在自己的服务器上用，谢谢了！盼复。

**Comment by wdjoys** [comment]
https://hostloc.com/thread-865778-1-1.html

**Comment by nashgoo** [comment]
> https://hostloc.com/thread-865778-1-1.html
Traceback (most recent call last):
  File "docker_start.py", line 22, in <module>
    config_obj.read(CONFIG_PATH, encoding="UTF-8")
  File "/usr/local/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/pt-tools/config/config.ini' [line 19]: option "'url'" in section 'NexusPHP' already exists

docker logs得到上述反馈，请问是什么原因

**Comment by wdjoys** [comment]
配置文件格式有问题。按照例子来

**Comment by nashgoo** [comment]
> 配置文件格式有问题。按照例子来

按照dockerhub上提供的配置文件要求，反复试了几次，基本上都是提示错误。麻烦帮忙看看具体是哪里不对路。

Traceback (most recent call last):
  File "run.py", line 11, in <module>
    eval('%s()' % action)
  File "<string>", line 1, in <module>
  File "/pt-tools/NexusPHP/tasks/sign_in.py", line 25, in main
    [signIn(config['session'], config['url'])
  File "/pt-tools/NexusPHP/tasks/sign_in.py", line 25, in <listcomp>
    [signIn(config['session'], config['url'])
  File "/pt-tools/NexusPHP/tasks/sign_in.py", line 16, in signIn
    with session.get(attendanceUrl) as res:
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pthome.net', port=443): Max retries exceeded with url: /attendance.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8b1a330a0>: Failed to establish a new connection: [Errno -3] Try again'))

各种格式都没有改，连空格啥的都没有改

**Comment by nashgoo** [comment]
> 配置文件格式有问题。按照例子来

按照dockerhub上提供的配置文件要求，反复试了几次，基本上都是提示错误。麻烦帮忙看看具体是哪里不对路。

Traceback (most recent call last):
  File "run.py", line 11, in <module>
    eval('%s()' % action)
  File "<string>", line 1, in <module>
  File "/pt-tools/NexusPHP/tasks/sign_in.py", line 25, in main
    [signIn(config['session'], config['url'])
  File "/pt-tools/NexusPHP/tasks/sign_in.py", line 25, in <listcomp>
    [signIn(config['session'], config['url'])
  File "/pt-tools/NexusPHP/tasks/sign_in.py", line 16, in signIn
    with session.get(attendanceUrl) as res:
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pthome.net', port=443): Max retries exceeded with url: /attendance.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8b1a330a0>: Failed to establish a new connection: [Errno -3] Try again'))

各种格式都没有改，连空格啥的都没有改

**Comment by wdjoys** [comment]
贴配置文件，关键信息用星号。

**Comment by nashgoo** [comment]
> 贴配置文件，关键信息用星号。

搞定了，docker重新安装就好了，谢谢您嘞

**Comment by nashgoo** [comment]
10个PT站的 尝试，现在是海胆和btschool没办法做到自动签到，52pt需要答题这个没办法，能不能看看前述两个行不行？

**Comment by nashgoo** [comment]
今天发现有错误，一直都是报错，是有什么问题吗？
